### ISSUE TITLE
NEXT BowlingJS: Tuesday 12th July 19:00 Elephant & Castle Palace!

### ISSUE THREAD

**Issue by nelsonic** [bowlingjs/bowlingjs.github.io#15]
@bowlingjs/owners + Everyone You Know,
Bowling lanes are booked for tomorrow evening 19:00 under my name (Nelson).
Usual place:  [Palace Superbowl, Elephant & Castle, SE1 6TE](https://www.google.co.uk/maps/place/Elephant+%26+Castle+Shopping+Centre/@51.493675,-0.099306,17z/data=!3m1!4b1!4m2!3m1!1s0x487604a203170f4b:0xa40d195532440ae)
Who ever arrives first check in and get party started. 🎉

**Comment by alanshaw** [comment]
🎳 🚀
