### ISSUE TITLE
Order Stickers

### ISSUE THREAD

**Issue by nelsonic** [bowlingjs/bowlingjs.github.io#5]
As per Gitter Chat:

![bowlingjs-stickers](https://cloud.githubusercontent.com/assets/194400/4841091/c4a695e8-6016-11e4-91c5-a15a92077b74.png)

Order stickers from: http://stickerapp.co.uk/

https://github.com/bowlingjs/bowlingjs.github.io/blob/master/logo.svg

**Comment by iteles** [comment]
Done & Done :+1: 
![img_1972](https://cloud.githubusercontent.com/assets/4185328/6348550/96613d42-bc18-11e4-9163-4537faf56b3e.jpg)
